- name: install MySQL server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: start and enable mysql server
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: install botocore and boto3
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - boto3
  - botocore

# - name: setup root password
#   ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ MYSQL_ROOT_PASSWORD }}"

- name: install pymysql
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip3


- name: setup root password for localhost
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: root
    host: localhost
    password: "{{ MYSQL_ROOT_PASSWORD }}"
    state: present

- name: allow remote root access
  community.mysql.mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: root
    host: "%"
    password: "{{ MYSQL_ROOT_PASSWORD }}"
    priv: "*.*:ALL,GRANT"
    state: present
