- name: install MySQL server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: start and enable mysql server
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: install botocore and boto3
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - boto3
  - botocore

- name: install pip
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: install python mysql dependencies
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3

- name: setup root password localhost
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ MYSQL_ROOT_PASSWORD }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    plugin: mysql_native_password
    state: present

- name: setup root password remote
  community.mysql.mysql_user:
    name: root
    host: "%"
    password: "{{ MYSQL_ROOT_PASSWORD }}"
    login_user: root
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    plugin: mysql_native_password
    priv: "*.*:ALL,GRANT"
    state: present